// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_TpQN4AXD2KZBwdgab6-a621k7USqBSw',
    appId: '1:581190398553:web:f489565484b8ebd8f13748',
    messagingSenderId: '581190398553',
    projectId: 'sportifyapp-1418b',
    authDomain: 'sportifyapp-1418b.firebaseapp.com',
    storageBucket: 'sportifyapp-1418b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMXFvLbe7jp7f_rxgX8gqTdY5_iAV0Bjw',
    appId: '1:581190398553:android:af01e2fc89b66818f13748',
    messagingSenderId: '581190398553',
    projectId: 'sportifyapp-1418b',
    storageBucket: 'sportifyapp-1418b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbcejHOmIMOs4MVeMOB651fgjeP7oLn_E',
    appId: '1:581190398553:ios:a8e3a2467ef85efff13748',
    messagingSenderId: '581190398553',
    projectId: 'sportifyapp-1418b',
    storageBucket: 'sportifyapp-1418b.appspot.com',
    iosBundleId: 'com.example.sportifyApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbcejHOmIMOs4MVeMOB651fgjeP7oLn_E',
    appId: '1:581190398553:ios:0a6a3474a5f744e4f13748',
    messagingSenderId: '581190398553',
    projectId: 'sportifyapp-1418b',
    storageBucket: 'sportifyapp-1418b.appspot.com',
    iosBundleId: 'com.example.sportifyApplication.RunnerTests',
  );
}
